name: 🐞 Bug Report
description: Report a bug with MockBukkit.
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Describe the bug in as much detail as you can.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducible Test
      description: Please write a test that can reliably reproduce the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
