name: Build

on:
  pull_request:
    branches: [ v1.* ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Read repo contents
      checks: write # Write result from pipeline execution

    steps:
      - uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle 8.10
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test --refresh-dependencies

      - name: Validate checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
      - name: Comment PR with checkstyle issues
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'build/reports/checkstyle/**.xml'
